[build]
  publish = "."
  command = "npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# Redirect for SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdnjs.cloudflare.com https://cdn.jsdelivr.net https://unpkg.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; media-src 'self' blob:; connect-src 'self' https://api-inference.huggingface.co https://cdn.jsdelivr.net https://unpkg.com; worker-src 'self' blob:; child-src blob:; object-src 'none';"
    
# API function headers
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"

# Cache static assets
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Environment variables for production
[context.production.environment]
  HUGGINGFACE_API_KEY = "your_actual_api_key_here"

# Environment variables for branch deploys (optional)
[context.branch-deploy.environment]
  HUGGINGFACE_API_KEY = "demo_key_for_testing"

# Development environment
[context.dev.environment]
  HUGGINGFACE_API_KEY = "demo_key_for_development"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "https://cdn.jsdelivr.net/npm/@mediapipe/*/**.js"
  [headers.values]
    Content-Type = "application/javascript"
